# Generated by Django 3.0.2 on 2020-01-19 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VKApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_secret', models.CharField(max_length=256)),
                ('scopes', models.CharField(max_length=256)),
                ('display', models.CharField(max_length=256)),
                ('client_secret_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VKConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=356)),
                ('vk_first_name', models.CharField(max_length=256)),
                ('vk_last_name', models.CharField(max_length=256)),
                ('vk_user_id', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VKClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=356)),
                ('vk_client_name', models.CharField(max_length=256)),
                ('vk_client_id', models.IntegerField()),
                ('vk_account_name', models.CharField(max_length=256)),
                ('vk_account_id', models.IntegerField()),
                ('vk_page', models.CharField(max_length=256)),
                ('vk_page_access_token', models.CharField(max_length=356)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVKapp.VKConnection')),
            ],
        ),
    ]
