# Generated by Django 3.0.2 on 2020-01-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iVKapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VKApp',
        ),
    ]
