# Generated by Django 3.0.2 on 2020-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_secret', models.CharField(max_length=256)),
                ('scopes', models.CharField(max_length=256)),
                ('display', models.CharField(max_length=256)),
                ('client_secret_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='YandexApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=256)),
                ('client_secret', models.CharField(max_length=256)),
            ],
        ),
    ]
