# Generated by Django 3.0.2 on 2020-01-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iYandex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexDirectClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=356)),
                ('ya_client_login', models.CharField(max_length=256)),
                ('ya_client_id', models.IntegerField()),
                ('ya_agency_login', models.CharField(max_length=256, null=True)),
                ('ya_agency_id', models.IntegerField(null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iYandex.YandexConnection')),
            ],
        ),
        migrations.CreateModel(
            name='YandexMetrikaClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=356)),
                ('ya_login', models.CharField(max_length=256)),
                ('ya_id', models.IntegerField()),
                ('ya_metrika_id', models.IntegerField()),
                ('ya_metrika_name', models.CharField(max_length=256)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('direct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iYandex.YandexDirectClient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iYandex.YandexConnection')),
            ],
        ),
        migrations.DeleteModel(
            name='YandexApp',
        ),
    ]
